### ISSUE TITLE
Infografía: Esperanza Santiago Osorio.

### ISSUE THREAD

**Issue by EspeSanty** [SistemasTecTlaxiaco/aplicacion-con-realidad-aumentada-EspeSanty#2]
![realidad aumentada y realidad virtual](https://user-images.githubusercontent.com/64815213/111771558-7923bf80-8871-11eb-903f-023ca6ea69f8.jpg)

**Comment by AxayacatlS** [comment]
Calificación 18

**Comment by josealfredo79** [comment]
esta bien hecho..solo que la actividad esta fuera de tiempo...
