### ISSUE TITLE
practica1Esperanza

### ISSUE THREAD

**Issue by EspeSanty** [SistemasTecTlaxiaco/aplicacion-con-realidad-aumentada-EspeSanty#3]
[practica1realidadauementadaEsperanza.pdf](https://github.com/SistemasTecTlaxiaco/aplicacion-con-realidad-aumentada-EspeSanty/files/6183893/practica1realidadauementadaEsperanza.pdf)

**Comment by AxayacatlS** [comment]
Calificación: 18

**Comment by josealfredo79** [comment]
Este trabajo esta bien hecho...solo que esta fuera de tiempo
